default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: admin
  password: adminpass

development:
  <<: *default
  database: try_again_rails_development

test:
  <<: *default
  database: try_again_rails_test

production:
  <<: *default
  database: try_again_rails_production
